# SD_to_Video clocks. The board oscillator is 50 MHz. derive_clocks reads
# the PLL configuration, including the 180-degree SDRAM phase-shifted output;
# the following commands give those generated clocks stable project names.
create_clock -name {clk} -period 20.000 -waveform {0.000 10.000} [get_ports {clk}]
derive_clocks

rename_clock -name {sd_card_clk} -source [get_ports {clk}] -master_clock {clk} [get_pins {sys_pll_m0/pll_inst.clkc[0]}]
rename_clock -name {ext_mem_clk} -source [get_ports {clk}] -master_clock {clk} [get_pins {sys_pll_m0/pll_inst.clkc[1]}]
rename_clock -name {ext_mem_clk_sft} -source [get_ports {clk}] -master_clock {clk} [get_pins {sys_pll_m0/pll_inst.clkc[2]}]
rename_clock -name {video_clk} -source [get_ports {clk}] -master_clock {clk} [get_pins {video_pll_m0/pll_inst.clkc[0]}]
rename_clock -name {hdmi_5x_clk} -source [get_ports {clk}] -master_clock {clk} [get_pins {video_pll_m0/pll_inst.clkc[1]}]

# The two PLLs and the direct 50 MHz control domain have no guaranteed mutual
# phase. All crossings between these groups use synchronizers, toggles, or
# asynchronous FIFOs. Clocks generated by the same PLL remain related so TD
# still analyzes SD/SDRAM and pixel/serializer timing correctly.
set_clock_groups -asynchronous \
    -group [get_clocks {clk}] \
    -group [get_clocks {sd_card_clk ext_mem_clk ext_mem_clk_sft}] \
    -group [get_clocks {video_clk hdmi_5x_clk}]
