/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/AnLuTD_Project/SD_to_Video/prj/al_ip/audio_fifo_32x4096.v
 ** Date	:	2026 09 06
 ** TD version	:	6.2.168116
************************************************************/

`timescale 1ns / 1ps

module audio_fifo_32x4096 (
	rst,
	di, clkw, we,
	do, clkr, re,
	empty_flag,
        full_flag
);

	input rst;
	input [31:0] di;
	input clkw, we;
	input clkr,re;

	output [31:0] do;
	output empty_flag;
	output full_flag;

EG_LOGIC_FIFO #(
        .DATA_WIDTH_W(32),
	.DATA_WIDTH_R(32),
	.DATA_DEPTH_W(4096),
	.DATA_DEPTH_R(4096),
	.ENDIAN("LITTLE"),
	.RESETMODE("ASYNC"),
	.E(0),
	.F(4096),
	.ASYNC_RESET_RELEASE("SYNC"))
fifo_inst(
	.rst(rst),
	.di(di),
	.clkw(clkw),
	.we(we),
	.csw(3'b111),
	.do(do),
	.clkr(clkr),
	.re(re),
	.csr(3'b111),
	.ore(1'b0),
	.empty_flag(empty_flag),
	.aempty_flag(),
	.full_flag(full_flag),
	.afull_flag()

);

endmodule
