--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/zbrmyyds/Desktop/anlu/FPGA_Prj/I2S/transmitor/APUG092_HDMI1.4b_Transmitter_V1.0/src/td_project/al_ip/AUDIO_SAMPLE_ROM.vhd
 -- Date	:	2026 04 10
 -- TD version	:	6.2.168116
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY AUDIO_SAMPLE_ROM IS
PORT (
	doa		: OUT STD_LOGIC_VECTOR(23 DOWNTO 0);

	addra	: IN STD_LOGIC_VECTOR(5 DOWNTO 0);
	clka		: IN STD_LOGIC
	);
END AUDIO_SAMPLE_ROM;

ARCHITECTURE struct OF AUDIO_SAMPLE_ROM IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 24,
			ADDR_WIDTH_A	=> 6,
			DATA_DEPTH_A	=> 48,
			DATA_WIDTH_B	=> 24,
			ADDR_WIDTH_B	=> 6,
			DATA_DEPTH_B	=> 48,
			MODE			=> "SP",
			REGMODE_A	=> "NOREG",
			IMPLEMENT	=> "9K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "../../user_source/hdl_source/python/audio_sine_24bit_48deep_scale8.mif",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia		=> (others=>'0'),
			dib		=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea		=> '1',
			ceb		=> '0',
			clka		=> clka,
			clkb		=> '0',
			web		=> '0',
			rsta		=> '0',
			rstb		=> '0',
			doa		=> doa,
			dob		=> OPEN,
			ocea		=> '0',
			oceb		=> '0'
		);

END struct;
