/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/zbrmyyds/Desktop/anlu/FPGA_Prj/I2S/transmitor/APUG092_HDMI1.4b_Transmitter_V1.0/src/td_project/al_ip/AUDIO_SAMPLE_ROM.v
 ** Date	:	2026 04 10
 ** TD version	:	6.2.168116
************************************************************/

`timescale 1ns / 1ps

module AUDIO_SAMPLE_ROM ( doa, addra, clka );

	output [23:0] doa;

	input  [5:0] addra;
	input  clka;



	EG_LOGIC_BRAM #( .DATA_WIDTH_A(24),
				.ADDR_WIDTH_A(6),
				.DATA_DEPTH_A(48),
				.DATA_WIDTH_B(24),
				.ADDR_WIDTH_B(6),
				.DATA_DEPTH_B(48),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../../user_source/hdl_source/python/audio_sine_24bit_48deep_scale8.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({24{1'b0}}),
				.dib({24{1'b0}}),
				.addra(addra),
				.addrb({6{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule