--------------------------------------------------------------
 --  Copyright (c) 2012-2025 Anlogic Inc. --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/AnLuTD_Project/SD_to_Video/prj/al_ip/scaler_linebuf_odd_ip.vhd
 -- Date	:	2026 09 14
 -- TD version	:	6.2.168116
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY scaler_linebuf_odd_ip IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(23 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(23 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(10 DOWNTO 0);
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(10 DOWNTO 0);
	clkb	: IN STD_LOGIC;
	rstb	: IN STD_LOGIC
	);
END scaler_linebuf_odd_ip;

ARCHITECTURE struct OF scaler_linebuf_odd_ip IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 24,
			DATA_WIDTH_B	=> 24,
			ADDR_WIDTH_A	=> 11,
			ADDR_WIDTH_B	=> 11,
			DATA_DEPTH_A	=> 2048,
			DATA_DEPTH_B	=> 2048,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "OUTREG",
			WRITEMODE_A	=> "WRITETHROUGH",
			WRITEMODE_B	=> "NORMAL",
			RESETMODE	=> "SYNC",
			IMPLEMENT		=> "32K",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> '1',
			clka	=> clka,
			clkb	=> clkb,
			wea	=> '1',
			bea	=> (others=>'0'),
			web	=> '0',
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> '1',
			rsta	=> '0',
			rstb	=> rstb,
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
