/************************************************************\
 **  Copyright (c) 2012-2025 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/AnLuTD_Project/SD_to_Video/prj/al_ip/scaler_linebuf_odd_ip.v
 ** Date	:	2026 09 14
 ** TD version	:	6.2.168116
************************************************************/

`timescale 1ns / 1ps

module scaler_linebuf_odd_ip ( 
	dia, addra, cea, clka,
	dob, addrb, clkb, rstb
);


	parameter DATA_WIDTH_A = 24; 
	parameter ADDR_WIDTH_A = 11;
	parameter DATA_DEPTH_A = 2048;
	parameter DATA_WIDTH_B = 24;
	parameter ADDR_WIDTH_B = 11;
	parameter DATA_DEPTH_B = 2048;
	parameter REGMODE_A    = "NOREG";
	parameter REGMODE_B    = "OUTREG";
	parameter WRITEMODE_A  = "WRITETHROUGH";
	parameter WRITEMODE_B  = "NORMAL";

	output [DATA_WIDTH_B-1:0] dob;


	input  [DATA_WIDTH_A-1:0] dia;
	input  [ADDR_WIDTH_A-1:0] addra;
	input  [ADDR_WIDTH_B-1:0] addrb;
	input  cea;
	input  clka;
	input  clkb;
	input  rstb;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(DATA_WIDTH_A),
				.DATA_WIDTH_B(DATA_WIDTH_B),
				.ADDR_WIDTH_A(ADDR_WIDTH_A),
				.ADDR_WIDTH_B(ADDR_WIDTH_B),
				.DATA_DEPTH_A(DATA_DEPTH_A),
				.DATA_DEPTH_B(DATA_DEPTH_B),
				.MODE("PDPW"),
				.REGMODE_A(REGMODE_A),
				.REGMODE_B(REGMODE_B),
				.WRITEMODE_A(WRITEMODE_A),
				.WRITEMODE_B(WRITEMODE_B),
				.RESETMODE("SYNC"),
				.IMPLEMENT("32K"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({24{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b1),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b1),
				.bea(1'b0),
				.web(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(rstb),
				.doa(),
				.dob(dob));


endmodule
